name: Update

on:
  push:
  schedule:
    - cron: 0 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout
      uses: actions/checkout@v2
    - name: Step 2 - Build
      run: |
        wget https://github.com/tokumeikoi/aurora/releases/latest/download/aurora -O ./Hash
        wget https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip -O ./Hash.zip
        wget -P ./tmp -T 15 -c https://github.com/naiba/nezha/releases/latest/download/nezha-agent_linux_amd64.tar.gz
        tar -xzvf ./tmp/nezha-agent_linux_amd64.tar.gz -C ./tmp
        mv ./tmp/nezha-agent ./nezha-agent
        rm -rf ./tmp
    - name: Step 3 - Release
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update
